### ISSUE TITLE
parameters in the basic.js

### ISSUE THREAD

**Issue by petrunka** [ncb000gt/node-googleanalytics#32]
Which values should be assigned to the parameters profile, username and password?

**Comment by boboci9** [comment]
Hi,
Sorry for the lame question but I get Invalid credentials every time I try setting up my account,
I can log in with my email and password to the google analytics site but here I get Invalid credentials.
Any ideas why? Also how can I set up a token so I don't divulge my password when I commit my code?

Thanks in advance.
