### ISSUE TITLE
Unspecified error

### ISSUE THREAD

**Issue by IgorDePaula** [ncb000gt/node-googleanalytics#39]
I tryed your exemple and I received this:

![errror google analytics](https://cloud.githubusercontent.com/assets/2833993/8479488/7a4d28a0-20ae-11e5-8da9-6d5dc334c3a4.png)

**Comment by Oldwo1f** [comment]
I got the same problem with an app whilch was working. And now i got this error.

**Comment by Oldwo1f** [comment]
Anyone else got this issue?

Its very strange and it's look like it is inside ga lib line 91

**Comment by richdunajewski** [comment]
:+1: Same issue. Maybe the API changed?

**Comment by Oldwo1f** [comment]
Yeah its a big bug. I got this since a month and none answer.

I am considering changing lib..

**Comment by Oldwo1f** [comment]
Hi every one, 2 months later i would like to know if someone found a solution for this.

It still does'nt work for me.

**Comment by IgorDePaula** [comment]
I thin that author abandoned this project.

2015-09-04 8:54 GMT-03:00 Oldwo1f <notifications@github.com>:

**Comment by Oldwo1f** [comment]
did you find a way to use goodanalityc in node projects?

2015-09-04 14:10 GMT+02:00 Igor C. de Paula <notifications@github.com>:

**Comment by IgorDePaula** [comment]
No, No yet.

2015-09-04 9:11 GMT-03:00 Oldwo1f <notifications@github.com>:

**Comment by ncb000gt** [comment]
Sorry. I haven't exactly abandoned any projects, I'm just extremely busy with other stuff so I don't have a lot of time to spend on my side projects. And then, the projects that tend to get attention are the ones I use. I haven't used this project in years. =\

I'd be happy to accept pull requests.

**Comment by Oldwo1f** [comment]
Ok no problem man.

But the thing is :  Your project was working and all of a sudden it dont.
Maybe you can provide a little help to help to identify that bug. Then i ll
try to fix it and make a pull request

2015-09-04 18:55 GMT+02:00 Nick Campbell <notifications@github.com>:

**Comment by ncb000gt** [comment]
So, I looked around briefly and it looks like the ClientLogin api no longer works.

It requires OAuth 2.0 to use the apis...

https://developers.google.com/identity/protocols/AuthForInstalledApps

**Comment by IgorDePaula** [comment]
Sorry, man, I understand. I think that we can close this issue, yes?

**Comment by Oldwo1f** [comment]
yes you can

2015-09-06 14:13 GMT+02:00 Igor C. de Paula <notifications@github.com>:
